#!/usr/bin/env bash

echo "Finding what must be compiled"

PATHS=`nix-build --dry-run build.nix 2> /dev/stdout | grep '\.drv$' | sed -e 's/^[ \t]*//'`

echo "The following paths with be build:"
for p in $PATHS; do
    echo $p
done

REALIZED=`
for p in $PATHS; do
    nix-store --realize $p --verbose
done
`

echo "These are the paths's closures:"
for r in $REALIZED; do
    echo $r
done

echo "Exporting..."
nix-store --export $REALIZED > out.nar
