#!/usr/bin/env bash
PATHS=`nix-build --dry-run build.nix 2> /dev/stdout | grep '\.drv$' | sed -e 's/^[ \t]*//'`

nix-store --export $(
for p in $PATHS; do
    nix-store --realize $p --verbose
done
) > out.nar
echo "$PATHS"
