#!/usr/bin/env bash

TEMPFILE=`mktemp`.nix

echo '
let
    flake-compat = builtins.fetchTarball {
        url = "https://github.com/edolstra/flake-compat/archive/master.tar.gz";
    };
in
' > $TEMPFILE

function usage {
    echo "
$(tput bold)options$(tput sgr0) [my flags] [option] [nixos-option flags]

$(tput bold)my flags$(tput sgr0)
    --flake: which flake with configuration to inspect
        Example: .#nixosConfigurations.main
    -h, --help: show this help message

$(tput bold)option$(tput sgr0)
    --flake: which flake with configuration to inspect
    the option to be inspected in the same format as is in nixos-option

$(tput bold)nixos-option flags$(tput sgr0)
    Same as nixos-option (8)
    "
}

while true; do
    case "$1" in
        --help | -h)
            usage
            exit 0
        ;;
        --flake)
            shift
            IFS='#' read -a FLAKE_PARTS <<< "$1"
            shift
            echo "$FLAKE_PARTS"
            if [[ "${FLAKE_PARTS[0]}" =~ ^[./] ]]; then
                DIR=`cd "${FLAKE_PARTS[0]}"; pwd`
                echo "(import flake-compat {src = \"$DIR\";}).defaultNix.${FLAKE_PARTS[1]}" >> $TEMPFILE
            else
                echo "(import flake-compat {src = \"${FLAKE_PARTS[0]}\";}).defaultNix.${FLAKE_PARTS[1]}" >> $TEMPFILE
            fi
        ;;
        *)
            break
        ;;
    esac
done

nixos-option --config_expr "(import $TEMPFILE).config" --options_expr "(import "$TEMPFILE").options" "$@"
