#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

VERSION=0.0.8

case "$(uname -s)" in
    Linux*)     GOOS=linux ;;
    Darwin*)    GOOS=darwin ;;
    FreeBSD*)   GOOS=freebsd ;;
    *)          GOOS=linux ;;
esac

case "$(uname -m)" in
    x86_64*)    GOARCH=amd64 ;;
    arm64*)     GOARCH=arm64 ;;
    *)          GOARCH=amd64 ;;
esac

TMP=$(mktemp -d)
URL="https://github.com/lucasew/workspaced/releases/download/$VERSION/workspaced-$GOOS-$GOARCH"

wget -O "$TMP/workspaced" "$URL"

chmod +x $TMP/workspaced

echo $URL


$TMP/workspaced self-install -f

$TMP/workspaced apply
