#!/usr/bin/env bash

curl https://mise.run | sh

. ./bin/source_me

mkdir -p ~/.local/share/workspaced/bin

(
	cd "nix/pkgs/workspaced" || exit 1
	mise exec -- go build -o ~/.local/share/workspaced/bin/workspaced ./cmd/workspaced
)

systemctl restart --user workspaced

~/.local/share/workspaced/bin/workspaced dispatch apply
