{ ... }:
{
  imports = [
    ./cf-torrent.nix
    ./cloud-savegame.nix
    ./cockpit-extra.nix
    ./escrivao
    ./fusionsolar
    ./invidious.nix
    ./magnetico.nix
    ./miniflux.nix
    ./libreddit.nix
    ./transmission.nix
    ./telegram_sendmail.nix
    ./p2k.nix
    ./postgresql.nix
    ./nixgram.nix
    ./netusage
    ./restic-server.nix
    ./ollama.nix
    ./python-microservices
    ./rtorrent.nix
    ./rsyncnet
    ./wallabag.nix
    ./ts-proxy.nix
    ./ngircd.nix
    ./phputils
  ];
}
