// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getHistory = `-- name: GetHistory :many
SELECT id, command, cwd, timestamp, exit_code, duration_ms FROM history
ORDER BY timestamp DESC
LIMIT ?
`

func (q *Queries) GetHistory(ctx context.Context, limit int64) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Command,
			&i.Cwd,
			&i.Timestamp,
			&i.ExitCode,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHistory = `-- name: RecordHistory :exec
INSERT INTO history (command, cwd, timestamp, exit_code, duration_ms)
VALUES (?, ?, ?, ?, ?)
`

type RecordHistoryParams struct {
	Command    string
	Cwd        string
	Timestamp  int64
	ExitCode   int64
	DurationMs int64
}

func (q *Queries) RecordHistory(ctx context.Context, arg RecordHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordHistory,
		arg.Command,
		arg.Cwd,
		arg.Timestamp,
		arg.ExitCode,
		arg.DurationMs,
	)
	return err
}

const searchHistory = `-- name: SearchHistory :many
SELECT id, command, cwd, timestamp, exit_code, duration_ms FROM history
WHERE command LIKE ?
ORDER BY timestamp DESC
LIMIT ?
`

type SearchHistoryParams struct {
	Command string
	Limit   int64
}

func (q *Queries) SearchHistory(ctx context.Context, arg SearchHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, searchHistory, arg.Command, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Command,
			&i.Cwd,
			&i.Timestamp,
			&i.ExitCode,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
