[[language]]
name = "bash"
language-servers = ["bash-language-server", "typos-lsp"]

[[language]]
name = "markdown"
language-servers = ["ltex-ls", "typos-lsp"]

[[language]]
name = "nix"
language-servers = ["nil", "typos-lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "typos-lsp"]

[[language]]
name = "python"
language-servers = ["jedi-language-server", "ruff", "pylsp", "typos-lsp"]

[language-server.typos-lsp]
command = "typos-lsp"

[language-server.ltex-ls]
command = "ltex-ls"
